### ISSUE TITLE
Searching in URL bar, results go "above" bar

### ISSUE THREAD

**Issue by kewtz** [WesleyBranton/Remove-Firefox-Megabar#10] opened 2024-06-14 13:20 UTC
When using search, some search results extend "above" the URL bar. If I rename userChrome.css to userChrome.css.old - this issue no longer persists. 
![2024-06-14 09_18_48-Mozilla Firefox](https://github.com/WesleyBranton/Remove-Firefox-Megabar/assets/64649301/9b249fdb-dc5d-41c3-adf0-4f40dcdaf0b0)

Firefox 127.0

**Comment by kewtz** [comment] 2024-06-14 13:21
In the screenshot above, maps.google.com is within the URL bar and the cutoff portion is "above" the bar. 
It's not usable in this way.

**Comment by WesleyBranton** [comment] 2024-06-15 02:21
This is due to a recent change in Firefox. There is a [new userChrome.css file](https://github.com/WesleyBranton/Remove-Firefox-Megabar/releases/tag/v1.0.5) to address the issue. If you update the file, it should fix the problem.

**Comment by WesleyBranton** [comment] 2024-06-15 02:21
Duplicate of #8.

**Closed by WesleyBranton** 2024-06-15 02:21 UTC
Labels: duplicate
